### ISSUE TITLE
Allow copying of mobs from one avb to another

### ISSUE THREAD

**Issue by cbenhagen** [markreidvfx/pyavb#9]
It would be nice if this would work:
```python
with avb.open("source.avb") as f:
    with avb.open() as f2:
        for mob in f.content.mobs:
            f2.content.add_mob(mob)
        f2.write("destination.avb")
```

This currently results in:
```
Traceback (most recent call last):
  File "/path/to/script.py", line 42, in <module>
    f2.write("destination.avb")
  File "/Users/ben/.local/share/virtualenvs/avid_bin-DIzLLTwC/lib/python3.8/site-packages/avb/file.py", line 311, in write
    self.write_object(f, obj)
  File "/Users/ben/.local/share/virtualenvs/avid_bin-DIzLLTwC/lib/python3.8/site-packages/avb/file.py", line 278, in write_object
    obj.write(buffer)
  File "/Users/ben/.local/share/virtualenvs/avid_bin-DIzLLTwC/lib/python3.8/site-packages/avb/attributes.py", line 82, in write
    ctx = self.root.octx
AttributeError: 'AVBFile' object has no attribute 'octx'
```

**Comment by cbenhagen** [comment]
To give this some context: The goal for us would be to copy clips from daily sync bins to scene bins. It would be nice if the mobs would not need to be re-created from scratch. Any guidance on how to achieve this would be much appreciated. I am happy to contribute the final script back as an example.

**Comment by mjiggidy** [comment]
+1 on this!

**Comment by mjiggidy** [comment]
This may be info you've already discovered, but...

From what I can gather from reading the `pyavb` source, the `AVBFile object has no attribute 'octx'` issue is because the mobs' `.root` attributes are still referencing their original `AVBFile`s, which are open for reading so they only have an input context (`ictx`).  I've gotten past this by using `avb.core.walk_references()` to assign each of the mobs' `.root` to the output AVBFile, which will be given an output context (`octx`) when you call `AVBFile.write()`.  However, I'm not certain that's the proper way to do it -- it feels a bit brute-force to me, and I guess as a layman I would have expected this to be handled in `Bin.add_mob()` or something.

Also, I think there's more to it than *just* modifying the `.root` attributes, because I *sometimes* have success with this and *sometimes* not.  For example, here's a test I wrote to take the first sequence in a bin and copy it to a new bin.  This seems to work for *some* originating bins, but others produce `DOMAIN_COPYOUT_FAILED` errors when you try to open the new bins in Avid.

```python
#!/usr/bin/env python3

import avb

PATH_BIN_OLD = "/path/to/existing.avb"
PATH_BIN_NEW = "/path/to/new.avb"

with avb.open(PATH_BIN_OLD) as file_bin_old:

	# Get the first sequence in the old bin
	bin_old = file_bin_old.content
	seq = next(bin_old.toplevel())
	
	with avb.open() as file_new_bin:
		print(f"Adding {seq.name} to {PATH_BIN_NEW}")

		# Walk the mobs refereced by the sequence
		# Change the mob root to the new AVBFile and add the mob to the new bin
		for mob in avb.core.walk_references(seq):
			print(f"Modifying {mob}")
			mob.root = file_new_bin.content.root
			file_new_bin.content.add_mob(mob)

		file_new_bin.write(PATH_BIN_NEW)
```

**Comment by markreidvfx** [comment]
Yes this would be nice. Its a little involved because a mob references other mobs and objects. Those need to get copied as well for avid to to complain or crash.

**Comment by russellaugust** [comment]
@cbenhagen did you ever make progress with this?

**Comment by cbenhagen** [comment]
No unfortunately not.

**Comment by markreidvfx** [comment]
This is now possible in the 1.4 release.  
All `AVBObjects` now have a copy method, that can change the root object to another file.
The method handles all the tricky dependent references too.

```python

with avb.open("source.avb") as a:
    with avb.open() as b:
        for mob in a.content.mobs:
            new_mob = mob.copy(b)
            b.content.add_mob(new_mob)
        b.write("dest.avb")
```
mobs also have a `dependant_mobs` method too that returns mob dependencies.

for more examples look at `test_copy.py`

**Comment by mjiggidy** [comment]
This is gonna be big for me! Thank you so much!
